#!/bin/sh
FILE=${FILE:-$1}

date=`date +%Y-%b-%d-%H:%M:%S`
enc_file="${FILE}.age"

if [ ${#FILE} -eq 0 ];
then
  echo "No set file ENV"
  exit 2
fi

if [ ! -f $FILE ];
then
  echo "$FILE not exists"
  exit 2
fi

if [ ${#AGE_PUBLIC_KEY} -eq 0 ];
then
  echo "No set AGE_PUBLIC_KEY"
  exit 2
fi


RESTIC_PATH=restic
AGE_PATH=age

# Check that required tools is installed
age --version
if [ $? -gt 0 ];
then
  AGE_PATH=/tmp/age/age
  $AGE_PATH --version
  if [ $? -gt 0 ];
  then
    wget -O /tmp/age.tar.gz https://github.com/FiloSottile/age/releases/download/v1.0.0/age-v1.0.0-linux-amd64.tar.gz
    tar -xvf /tmp/age.tar.gz -C /tmp/
    chmod +x /tmp/age/age
  fi
fi

restic version
if [ $? -gt 0 ];
then
  RESTIC_PATH=/tmp/restic
  $RESTIC_PATH version
  if [ $? -gt 0 ];
  then
    wget -O /tmp/restic.bz2 https://github.com/restic/restic/releases/download/v0.14.0/restic_0.14.0_linux_amd64.bz2
    bzip2 -d /tmp/restic.bz2
    chmod +x /tmp/restic
  fi
fi

# Encrypt file
cat $FILE | $AGE_PATH -r $AGE_PUBLIC_KEY > $enc_file

# Init repo
$RESTIC_PATH init

# Create backup
$RESTIC_PATH backup $enc_file --verbose --tag ${BACKUP_TAG:-"backup"}

# Retention
forget_param=""
if [ ${#RETENTION_WITHIN} -gt 0 ];
then
forget_param="$forget_param --keep-within=${RETENTION_WITHIN}"
fi

if [ ${#RETENTION_DAILY} -gt 0 ];
then
forget_param="$forget_param --keep-daily=${RETENTION_DAILY}"
fi

if [ ${#RETENTION_WEEKLY} -gt 0 ];
then
forget_param="$forget_param --keep-weekly=${RETENTION_WEEKLY}"
fi

if [ ${#RETENTION_MONTHLY} -gt 0 ];
then
forget_param="$forget_param --keep-monthly=${RETENTION_MONTHLY}"
fi

if [ ${#RETENTION_YEARLY} -gt 0 ];
then
forget_param="$forget_param --keep-yearly=${RETENTION_YEARLY}"
fi

if [ ${#RETENTION_RAW} -gt 0 ];
then
forget_param="${RETENTION_RAW}"
fi

# Retention
if [ ${#forget_param} -gt 0 ];
then
  $RESTIC_PATH forget ${forget_param} --prune
fi
