#!/bin/sh

FILE=${FILE:-$1}

date=`date +%Y-%b-%d-%H:%M:%S`
enc_file="${FILE}.age"
RETENTION_MAX_FILES=${RETENTION_MAX_FILES:-100}
RETENTION_FILE_MAX_DAYS=${RETENTION_FILE_MAX_DAYS:-90}

if [ ${#FILE} -eq 0 ];
then
  echo "No set file ENV"
  exit 2
fi

if [ ! -f $FILE ];
then
  echo "$FILE not exists"
  exit 2
fi

# Check that required tools is installed
age --version
if [ $? -gt 0 ];
then
  wget -O /tmp/age.tar.gz https://github.com/FiloSottile/age/releases/download/v1.0.0/age-v1.0.0-linux-amd64.tar.gz
  tar -xvf /tmp/age.tar.gz
  chmod +x /tmp/age/age
  cp /tmp/age/age /usr/bin
fi

s5cmd version
if [ $? -gt 0 ];
then
  wget -O /tmp/s5cmd.tar.gz https://github.com/peak/s5cmd/releases/download/v2.0.0/s5cmd_2.0.0_Linux-64bit.tar.gz
  tar -xvf /tmp/s5cmd.tar.gz
  chmod +x /tmp/s5cmd
  mv /tmp/s5cmd /usr/bin
fi

# Encrypt file
cat $FILE | age -r $AGE_PUBLIC_KEY > $enc_file

# Copy to s3
s5cmd cp $enc_file s3://${S3_BUCKET}${S3_BUCKET_PATH}

